### ISSUE TITLE
Compliments

### ISSUE THREAD

**Issue by EasyG0ing1** [theparticleman/DonkeyKongAscii#1]
This is a great project and learning tool.  Within an hour I was able to get Mario to jump. Though for some reason in MacOS, the DonkeyKong and the Mario would not show up, so I had to replace the (char)1 and (char)2 in display.cs with just 'K' and 'M' respectively.

Thank you for the time you invested in this project.

Mike

**Comment by theparticleman** [comment]
I'm glad you enjoyed it! Thanks for mentioning the MacOS issue. I think I had someone else mention that to me, but I forgot about it. I'll add a note to the instructions.

**Comment by EasyG0ing1** [comment]
@theparticleman Good idea ... ironically how I found this project was from you mentioning your personal URL (I think) in a video you were in that was discussing Docker basics I believe ... you were like the guest teacher or something like that where you were streaming in from another location and I believe the video was originally a live presentation but I could be wrong about that...  I went straight to the URL you mentioned and totally forgot about watching the rest of the video after seeing this project. LOL

- I should mention that back in the 80's I was the master of any Donkey Kong arcade machine I met ... if I had quarters in my pocket ... :-)

Incidentally, what does the (char)1 and (char)2 display on operating systems where it actually works?

**Comment by theparticleman** [comment]
Haha! That's funny! I'm glad the code was interesting enough to distract you that much. :)

I lived in a small town when I was a kid, so I never really played Donkey Kong in the arcade. But I did play it on my older brother's Commodore 64!

On some systems `char(1)` and `char(2)` get rendered as two different smiley face characters: `☻` `☺`
Hopefully those two characters show up properly for you.
On my browser at least if I don't put the two smiley face characters in code blocks, Github renders the second one as a unicode smiley face emoji, but the first one still renders as an "ascii" character. In the command prompt (and Powershell) on Windows 10 (and older versions of Windows) both characters render as "ascii" smiley faces (hence why I used them in the original code). I'm not sure if the difference in rendering is a font thing or a code page thing or what. One day maybe I'll understand well enough how all that stuff works to know for sure. :)

I attached a screenshot so you can see what those two characters look like in the game on my machine.
![donkey kong ascii](https://user-images.githubusercontent.com/4561333/131036105-ad187254-6ca2-416d-8cf4-19e893575a51.png)
